production:
  adapter: redis
  url: redis://localhost:6379/1

development:
  adapter: redis
  url: redis://redistogo:3015e79cf0172da8a7539aa7258c5141@crestfish.redistogo.com:9910/

test:
  adapter: async
