meta_product_name: "Satoshi's Vision"
meta_title: "Craig Wright is a Fraud"
meta_description: "Edit the Bitcoin Whitepaper - 100 Sats per Word"
meta_image: "https://s3.us-east-2.amazonaws.com/toshi-vision-assets/twitter-meta.png"
twitter_account: "@i_amm_nobody"
